### ISSUE TITLE
У меня такой к вам вопрос

### ISSUE THREAD

**Issue by alexander3um** [sverinn/Marshalling-cpp-to-cs#1]
Здравствуйте, меня направили к вам. Говорят, вы устанавливаете майнкрафт без вирусов, можно у вас заказать установку майнкрафта без вирусов?

**Comment by sverinn** [comment]
> Здравствуйте, меня направили к вам. Говорят, вы устанавливаете майнкрафт без вирусов, можно у вас заказать установку майнкрафта без вирусов?

Здравствуйте, благодаря современным технологиям можно установить майнкрафт с вирусами. Слава господу нашему Иисусу Христу

**Comment by alexander3um** [comment]
> > Здравствуйте, меня направили к вам. Говорят, вы устанавливаете майнкрафт без вирусов, можно у вас заказать установку майнкрафта без вирусов?
> 
> Здравствуйте, благодаря современным технологиям можно установить майнкрафт с вирусами. Слава господу нашему Иисусу Христу

Благодарю, спасибо, вопрос закрыт.
